name: Publish Nethermind.Dirichlet.Numerics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-dirichlet:
    env:
      BUILD_CONFIG: release
      PROJECT_NAME: Nethermind.Dirichlet.Numerics
    name: Publish
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
    
      - name: Pack
        working-directory: ${{ env.PROJECT_NAME }}
        run: dotnet pack -c ${{ env.BUILD_CONFIG }}
    
      - name: Publish
        working-directory: ${{ env.PROJECT_NAME }}
        run: dotnet nuget push ${{ env.PROJECT_NAME }}/bin/${{ env.BUILD_CONFIG }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://apiint.nugettest.org/v3/index.json
